- ros_topic_name: "/lidar/x3"
  gz_topic_name: "/lidar/x3"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/X3/motor_speed"
  gz_topic_name: "/X3/gazebo/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

- ros_topic_name: "/X3/cmd_vel"
  gz_topic_name: "/X3/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: "ROS_TO_GZ"

- ros_topic_name: "/X3/enable"
  gz_topic_name: "/X3/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: "ROS_TO_GZ"